#version 450

#include "config.hpp"

layout(local_size_x = THREADS, local_size_y = THREADS) in;
layout(set = 1, binding = 0, r32f) uniform writeonly image2D writeImage;
layout(set = 2, binding = 0) uniform uniformValue
{
    float value;
};

void main()
{
    ivec2 size = imageSize(writeImage);
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);
    if (all(lessThan(id, size)))
    {
        imageStore(writeImage, id, vec4(value));
    }
}